// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint, type=warning, deprecated_member_use, deprecated_member_use_from_same_package
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'closed_caption_track_info.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$ClosedCaptionTrackInfo {
  /// Manifest URL of the associated track.
  Uri get url;

  /// Language of the associated track.
  Language get language;

  /// Whether the associated track was automatically generated.
  bool get isAutoGenerated;

  /// Track format
  ClosedCaptionFormat get format;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  $ClosedCaptionTrackInfoCopyWith<ClosedCaptionTrackInfo> get copyWith =>
      _$ClosedCaptionTrackInfoCopyWithImpl<ClosedCaptionTrackInfo>(
          this as ClosedCaptionTrackInfo, _$identity);

  /// Serializes this ClosedCaptionTrackInfo to a JSON map.
  Map<String, dynamic> toJson();

  @override
  bool operator ==(Object other) {
    final _this = this as ClosedCaptionTrackInfo;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ClosedCaptionTrackInfo &&
            (identical(other.url, _this.url) || other.url == _this.url) &&
            (identical(other.language, _this.language) ||
                other.language == _this.language) &&
            (identical(other.isAutoGenerated, _this.isAutoGenerated) ||
                other.isAutoGenerated == _this.isAutoGenerated) &&
            (identical(other.format, _this.format) ||
                other.format == _this.format));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode {
    final _this = this as ClosedCaptionTrackInfo;
    return Object.hash(runtimeType, _this.url, _this.language,
        _this.isAutoGenerated, _this.format);
  }
}

/// @nodoc
abstract mixin class $ClosedCaptionTrackInfoCopyWith<$Res> {
  factory $ClosedCaptionTrackInfoCopyWith(ClosedCaptionTrackInfo value,
          $Res Function(ClosedCaptionTrackInfo) _then) =
      _$ClosedCaptionTrackInfoCopyWithImpl;
  @useResult
  $Res call(
      {Uri url,
      Language language,
      bool isAutoGenerated,
      ClosedCaptionFormat format});

  $LanguageCopyWith<$Res> get language;
}

/// @nodoc
class _$ClosedCaptionTrackInfoCopyWithImpl<$Res>
    implements $ClosedCaptionTrackInfoCopyWith<$Res> {
  _$ClosedCaptionTrackInfoCopyWithImpl(this._self, this._then);

  final ClosedCaptionTrackInfo _self;
  final $Res Function(ClosedCaptionTrackInfo) _then;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? url = null,
    Object? language = null,
    Object? isAutoGenerated = null,
    Object? format = null,
  }) {
    return _then(ClosedCaptionTrackInfo(
      null == url
          ? _self.url
          : url // ignore: cast_nullable_to_non_nullable
              as Uri,
      null == language
          ? _self.language
          : language // ignore: cast_nullable_to_non_nullable
              as Language,
      isAutoGenerated: null == isAutoGenerated
          ? _self.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      format: null == format
          ? _self.format
          : format // ignore: cast_nullable_to_non_nullable
              as ClosedCaptionFormat,
    ));
  }

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $LanguageCopyWith<$Res> get language {
    return $LanguageCopyWith<$Res>(_self.language, (value) {
      return _then(_self.copyWith(language: value));
    });
  }
}

/// Adds pattern-matching-related methods to [ClosedCaptionTrackInfo].
extension ClosedCaptionTrackInfoPatterns on ClosedCaptionTrackInfo {
  /// A variant of `map` that fallback to returning `orElse`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeMap<TResult extends Object?>(
    TResult Function(_ClosedCaptionTrackInfo value)? $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _ClosedCaptionTrackInfo() when $default != null:
        return $default(_that);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// Callbacks receives the raw object, upcasted.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case final Subclass2 value:
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult map<TResult extends Object?>(
    TResult Function(_ClosedCaptionTrackInfo value) $default,
  ) {
    final _that = this;
    switch (_that) {
      case _ClosedCaptionTrackInfo():
        return $default(_that);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `map` that fallback to returning `null`.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case final Subclass value:
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? mapOrNull<TResult extends Object?>(
    TResult? Function(_ClosedCaptionTrackInfo value)? $default,
  ) {
    final _that = this;
    switch (_that) {
      case _ClosedCaptionTrackInfo() when $default != null:
        return $default(_that);
      case _:
        return null;
    }
  }

  /// A variant of `when` that fallback to an `orElse` callback.
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return orElse();
  /// }
  /// ```

  @optionalTypeArgs
  TResult maybeWhen<TResult extends Object?>(
    TResult Function(Uri url, Language language, bool isAutoGenerated,
            ClosedCaptionFormat format)?
        $default, {
    required TResult orElse(),
  }) {
    final _that = this;
    switch (_that) {
      case _ClosedCaptionTrackInfo() when $default != null:
        return $default(
            _that.url, _that.language, _that.isAutoGenerated, _that.format);
      case _:
        return orElse();
    }
  }

  /// A `switch`-like method, using callbacks.
  ///
  /// As opposed to `map`, this offers destructuring.
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case Subclass2(:final field2):
  ///     return ...;
  /// }
  /// ```

  @optionalTypeArgs
  TResult when<TResult extends Object?>(
    TResult Function(Uri url, Language language, bool isAutoGenerated,
            ClosedCaptionFormat format)
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _ClosedCaptionTrackInfo():
        return $default(
            _that.url, _that.language, _that.isAutoGenerated, _that.format);
      case _:
        throw StateError('Unexpected subclass');
    }
  }

  /// A variant of `when` that fallback to returning `null`
  ///
  /// It is equivalent to doing:
  /// ```dart
  /// switch (sealedClass) {
  ///   case Subclass(:final field):
  ///     return ...;
  ///   case _:
  ///     return null;
  /// }
  /// ```

  @optionalTypeArgs
  TResult? whenOrNull<TResult extends Object?>(
    TResult? Function(Uri url, Language language, bool isAutoGenerated,
            ClosedCaptionFormat format)?
        $default,
  ) {
    final _that = this;
    switch (_that) {
      case _ClosedCaptionTrackInfo() when $default != null:
        return $default(
            _that.url, _that.language, _that.isAutoGenerated, _that.format);
      case _:
        return null;
    }
  }
}

/// @nodoc
@JsonSerializable()
class _ClosedCaptionTrackInfo extends ClosedCaptionTrackInfo {
  const _ClosedCaptionTrackInfo(this.url, this.language,
      {this.isAutoGenerated = false, required this.format})
      : super._();
  factory _ClosedCaptionTrackInfo.fromJson(Map<String, dynamic> json) =>
      _$ClosedCaptionTrackInfoFromJson(json);

  /// Manifest URL of the associated track.
  @override
  final Uri url;

  /// Language of the associated track.
  @override
  final Language language;

  /// Whether the associated track was automatically generated.
  @override
  @JsonKey()
  final bool isAutoGenerated;

  /// Track format
  @override
  final ClosedCaptionFormat format;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  @pragma('vm:prefer-inline')
  _$ClosedCaptionTrackInfoCopyWith<_ClosedCaptionTrackInfo> get copyWith =>
      __$ClosedCaptionTrackInfoCopyWithImpl<_ClosedCaptionTrackInfo>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$ClosedCaptionTrackInfoToJson(
      this,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _ClosedCaptionTrackInfo &&
            (identical(other.url, url) || other.url == url) &&
            (identical(other.language, language) ||
                other.language == language) &&
            (identical(other.isAutoGenerated, isAutoGenerated) ||
                other.isAutoGenerated == isAutoGenerated) &&
            (identical(other.format, format) || other.format == format));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode {
    return Object.hash(runtimeType, url, language, isAutoGenerated, format);
  }
}

/// @nodoc
abstract mixin class _$ClosedCaptionTrackInfoCopyWith<$Res>
    implements $ClosedCaptionTrackInfoCopyWith<$Res> {
  factory _$ClosedCaptionTrackInfoCopyWith(_ClosedCaptionTrackInfo value,
          $Res Function(_ClosedCaptionTrackInfo) _then) =
      __$ClosedCaptionTrackInfoCopyWithImpl;
  @override
  @useResult
  $Res call(
      {Uri url,
      Language language,
      bool isAutoGenerated,
      ClosedCaptionFormat format});

  @override
  $LanguageCopyWith<$Res> get language;
}

/// @nodoc
class __$ClosedCaptionTrackInfoCopyWithImpl<$Res>
    implements _$ClosedCaptionTrackInfoCopyWith<$Res> {
  __$ClosedCaptionTrackInfoCopyWithImpl(this._self, this._then);

  final _ClosedCaptionTrackInfo _self;
  final $Res Function(_ClosedCaptionTrackInfo) _then;

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $Res call({
    Object? url = null,
    Object? language = null,
    Object? isAutoGenerated = null,
    Object? format = null,
  }) {
    return _then(_ClosedCaptionTrackInfo(
      null == url
          ? _self.url
          : url // ignore: cast_nullable_to_non_nullable
              as Uri,
      null == language
          ? _self.language
          : language // ignore: cast_nullable_to_non_nullable
              as Language,
      isAutoGenerated: null == isAutoGenerated
          ? _self.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
      format: null == format
          ? _self.format
          : format // ignore: cast_nullable_to_non_nullable
              as ClosedCaptionFormat,
    ));
  }

  /// Create a copy of ClosedCaptionTrackInfo
  /// with the given fields replaced by the non-null parameter values.
  @override
  @pragma('vm:prefer-inline')
  $LanguageCopyWith<$Res> get language {
    return $LanguageCopyWith<$Res>(_self.language, (value) {
      return _then(_self.copyWith(language: value));
    });
  }
}

// dart format on
